### ISSUE TITLE
ObjectStorageContainer#list fails with MessageBodyProviderNotFoundException

### ISSUE THREAD

**Issue by derjust** [gondor/openstack4j#347] opened 2015-04-24 17:21 UTC
Hi!

Trying to get a listing of the available containers via 
```java
List<? extends SwiftContainer> containers = objectStorage.containers().list();
```
fails with
```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain; charset=utf-8, type=class [Lorg.openstack4j.openstack.storage.object.domain.SwiftContainerImpl;, genericType=class [Lorg.openstack4j.openstack.storage.object.domain.SwiftContainerImpl;.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:225) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326) ~[jersey-client-2.10.1.jar:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111) ~[jersey-client-2.10.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:399) ~[jersey-common-2.10.1.jar:na]
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108) ~[jersey-client-2.10.1.jar:na]
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.readEntity(HttpResponseImpl.java:112) ~[openstack4j-jersey2-2.0.2.jar:na]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:56) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:19) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:62) ~[openstack4j-jersey2-2.0.2.jar:na]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:169) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:163) ~[openstack4j-2.0.2.jar:na]
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageContainerServiceImpl.list(ObjectStorageContainerServiceImpl.java:41) ~[openstack4j-2.0.2.jar:na]
```

Checking what is in the `InputStream` at `org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorContext):217` shows a `text/plain` representation of the expected output like
```
container1
container2
```

Setup:
Java: 1.8.0_40-b27
OpenStack4J: 2.0.2

**Comment by gondor** [comment] 2015-04-25 16:24
Do you mind switching to the recently released OpenStack4j 2.0.3.  This was fixed in that release.  See pull request: https://github.com/gondor/openstack4j/pull/312

If the issue is still appearing in 2.0.3 then please re-open/update this issue.

**Closed by gondor** 2015-04-25 16:24 UTC
