### ISSUE TITLE
ERROR: Unrecognized token 'EpointJWeb': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by sxjun1904** [gondor/openstack4j#363] opened 2015-05-08 01:49 UTC
when I want to list then objects:
[org.openstack4j.connectors.httpclient.HttpResponseImpl] ERROR: Unrecognized token 'EpointJWeb': was expecting ('true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@37d638ad; line: 1, column: 12]
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'EpointJWeb': was expecting ('true', 'false' or 'null')
 at [Source: org.apache.http.conn.EofSensorInputStream@37d638ad; line: 1, column: 12]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3323)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2482)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:1346)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1252)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:864)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:123)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:74)
	at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:68)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:159)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:154)
	at org.openstack4j.openstack.storage.object.internal.ObjectStorageObjectServiceImpl.list(ObjectStorageObjectServiceImpl.java:45)
	at com.test.Test.main(Test.java:33)

**Comment by gondor** [comment] 2015-05-08 04:54
What version of OpenStack4j?  This seems like a duplicate of a recent issue that was fixed.

**Comment by sxjun1904** [comment] 2015-05-08 05:37
Yes,This problem has been solved when I update to 2.0.3.thks

**Closed** 2015-05-10 13:36 UTC
