### ISSUE TITLE
ObjectStorage: file download

### ISSUE THREAD

**Issue by bassimatteo** [gondor/openstack4j#222] opened 2015-01-27 08:44 UTC
Hello,

I'm using Openstack4j with RestEasy Connector, using this snippet I'm not able to download a file:
```
OSClient.objectStorage().objects().download(container, fileName)
```
I get an exception from RestEasy, complaining that:
```
Unable to find a MessageBodyReader of content-type application/octet-stream and type class java.lang.Void
```

Is there a solution to solve the problem?

NOTE: I saw that in your ObjectStorageObjectServiceImpl class the method ```public DLPayload download(ObjectLocation location, DownloadOptions options)``` tries to convert the entity stream to a Void class. Maybe RestEasy is not accepting that.

**Comment by gondor** [comment] 2015-01-27 22:20
Thanks for the detailed information.  I was able to reproduce this and fix the cause.  Just checked in the code and re-deployed a new SNAPSHOT.  Let me know if this works

**Comment by bassimatteo** [comment] 2015-01-29 15:27
It works!

Thank you very much

**Comment by gondor** [comment] 2015-01-29 15:59
Great!

**Closed by gondor** 2015-01-29 15:59 UTC
Labels: bug

**Comment by bassimatteo** [comment] 2015-01-30 17:09
Trying to read a big (~30 MB) file, I got the following exception:
 ```
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:280)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream.read(SelfExpandingBufferredInputStream.java:57)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.jboss.resteasy.client.core.SelfExpandingBufferredInputStream.read(SelfExpandingBufferredInputStream.java:67)
 ```
It looks like in org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor, there's a method automatically closing the stream.
 ```
public void performReleaseConnection()
            {
               // Apache Client 4 is stupid, You have to get the InputStream and close it if there is an entity
               // otherwise the connection is never released. There is, of course, no close() method on response
               // to make this easier.
               try
               {
                  if (stream != null)
                  {
                     stream.close();
                  }
                  else
                  {
 ```
I also tried initializing the OSClient with:
```
'.withConfig(Config.newConfig().withReadTimeout(120000).withConnectionTimeout(120000))', 
```
but still no luck.
 
Do you think it's a RestEasy issue or can be fixed from your client ?

**Comment by bassimatteo** [comment] 2015-02-02 09:56
Maybe this could help you:
https://issues.jboss.org/browse/RESTEASY-1138

**Comment by vinodborole** [comment] 2016-02-25 12:40
@gondor @bassimatteo 

We are facing similar issue with 2.10 version of openstack4j-resteasy connector. Do we have a workaround for this?
